# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_number', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('prof', models.CharField(max_length=20)),
            ],
        ),
    ]
