# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.IntegerField(default=2, verbose_name='Enter time in 24-hour format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.IntegerField(default=0, verbose_name='Enter time in 24-hour format'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='prof',
            field=models.CharField(max_length=20, verbose_name='Enter proffessor name'),
        ),
    ]
