# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('prof', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('subject_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('room', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('time', models.CharField(choices=[('8:00am-8:55am', '8:00am-8:55am'), ('9:00am-9:55am', '9:00am-9:55am'), ('10:00am-10:55am', '10:00am-10:55am'), ('11:00am-11:55am', '11:00am-11:55am'), ('12:00pm-12:55pm', '12:00pm-12:55pm'), ('1:00pm-1:55pm', '1:00pm-1:55pm'), ('2:00pm-2:55pm', '2:00pm-2:55pm'), ('3:00pm-3:55pm', '3:00pm-3:55pm'), ('4:00pm-4:55pm', '4:00pm-4:55pm'), ('5:00pm-5:55pm', '5:00pm-5:55pm')], default='8:00am-8:55am', max_length=20)),
            ],
        ),
    ]
